FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list;   \
    sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list;  \
    apt-get update;

RUN apt-get install tightvncserver -y;
RUN apt-get install lxqt -y;
RUN apt-get install dbus-x11 -y;
RUN apt-get install binutils -y;
RUN strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5

WORKDIR /app

# RUN apt-get install git -y;

# RUN git clone https://github.com/novnc/noVNC
COPY ./noVNC ./noVNC
# RUN git clone https://github.com/novnc/websockify/
COPY ./websockify ./noVNC/utils/websockify

ENV DISPLAY=:0

EXPOSE 80

CMD rm -rf /tmp/.X0-lock&Xvnc :0 -geometry 1920x1080 -depth 24&startlxqt&./noVNC/utils/novnc_proxy --vnc :5900 --listen 80